[mcp_servers.dart]
command = "dart"
args = ["mcp-server"]

[mcp_servers.mobile]
command = "npx"
args = [
    "-y",
    "@mobilenext/mobile-mcp@latest",
]

[mcp_servers.playwright]
command = "npx"
args = [
    "-y",
    "@playwright/mcp@latest",
]

[mcp_servers.supabase]
url = "https://mcp.supabase.com/mcp"
